package com.team.yeogibeoryeo.presentation.common.design

import androidx.compose.ui.graphics.Color

object AppAccentColors {
    val MainCyan = Color(0xFF06B6D4)
    val DarkSlate = Color(0xFF1E293B)
    val PointBlue = Color(0xFF2563EB)
    val SoftCyan = Color(0xFFE8FAFD)
    val SoftBlue = Color(0xFFEAF1FF)
    val Mint = Color(0xFF10B981)
    val SoftMint = Color(0xFFE8FBF4)
    val Orange = Color(0xFFF97316)
    val SoftOrange = Color(0xFFFFF0E8)
    val Violet = Color(0xFF8B5CF6)
    val SoftViolet = Color(0xFFF2ECFF)
    val Rose = Color(0xFFE11D48)
    val SoftRose = Color(0xFFFFEDF2)
    val Amber = Color(0xFFF59E0B)
    val SoftAmber = Color(0xFFFFF7E6)
    val Teal = Color(0xFF0F766E)
    val SoftTeal = Color(0xFFE8F7F5)
    val Indigo = Color(0xFF4F46E5)
    val SoftIndigo = Color(0xFFEEF0FF)
    val Lime = Color(0xFF65A30D)
    val SoftLime = Color(0xFFF4F9E8)
    val Brown = Color(0xFF92400E)
    val SoftBrown = Color(0xFFF8EEE7)
    val Magenta = Color(0xFFC026D3)
    val SoftMagenta = Color(0xFFFAEAFE)
    val Sky = Color(0xFF0284C7)
    val SoftSky = Color(0xFFE8F5FC)
    val Red = Color(0xFFDC2626)
    val SoftRed = Color(0xFFFDECEC)
    val Coral = Color(0xFFEA580C)
    val SoftCoral = Color(0xFFFFEEE7)
    val Olive = Color(0xFF4D7C0F)
    val SoftOlive = Color(0xFFF0F7E8)
    val Brick = Color(0xFFC2410C)
    val SoftBrick = Color(0xFFFFEFE9)
    val Gray = Color(0xFF64748B)
    val SoftGray = Color(0xFFF1F5F9)
    val SoftGrayStrong = Color(0xFFE2E8F0)
    val ScreenBackground = Color(0xFFF8FAFC)
}
